import type { ProgramMeta } from "../react/types.d.ts";

export function createSetupScript(programs: ProgramMeta[]): string {
  const header = `# Mac Setup Script\n# Generated by Mac Setup Store\n`;
  const body = programs
    .map((p) => `# ${p.name}\n# TODO: add commands for ${p.slug || p.id}\n`)
    .join("\n");
  return header + body;
}
