id: "dbngin"
name: "DBngin"
description: "Simple database management tool"
type: "brew_cask"
category: "Utilities"
selected_by_default: false
requires_license: false
tags:
  - database
  - mysql
  - postgresql
  - redis
  - development
  - management
url: "https://dbngin.com/"
notes: |
  - Simple database server management for developers
  - Support for MySQL, PostgreSQL, and Redis
  - Easy start/stop database services
  - Version management and switching
  - Minimal configuration required
  - Free for personal use with pro features available
dependencies: []
install: |
  echo "Installing DBngin..."
  brew install --cask dbngin
validate: |
  brew list --cask | grep -q "dbngin" || ls /Applications/ | grep -q "DBngin.app"
configure: |
  echo "DBngin configuration complete"
  echo "Launch DBngin to start managing your databases"
  echo ""
  echo "Key features:"
  echo "- Simple start/stop for database services"
  echo "- Support for MySQL, PostgreSQL, and Redis"
  echo "- Multiple database versions side by side"
  echo "- Automatic service management"
  echo "- Connection string generation"
  echo "- Minimal system resource usage"
  echo ""
  echo "Supported databases:"
  echo "- MySQL (multiple versions)"
  echo "- PostgreSQL (multiple versions)"
  echo "- Redis (key-value store)"
  echo ""
  echo "Getting started:"
  echo "1. Launch DBngin from Applications"
  echo "2. Install desired database versions"
  echo "3. Start/stop services with simple toggles"
  echo "4. Use generated connection strings in your apps"
  echo "5. Switch between versions as needed"
  echo ""
  echo "Benefits for developers:"
  echo "- No complex database setup or configuration"
  echo "- Quick switching between database versions"
  echo "- Clean uninstallation of database services"
  echo "- Resource-efficient background operation"
  echo "- Integration with development workflows"
  echo ""
  echo "Database management:"
  echo "- Install/uninstall database versions"
  echo "- Start/stop services individually"
  echo "- View connection details and ports"
  echo "- Access database logs and configuration"
  echo "- Import/export database dumps"
  echo ""
  echo "Use cases:"
  echo "- Local development database servers"
  echo "- Testing applications with different DB versions"
  echo "- Learning database administration"
  echo "- Prototyping and experimentation"
  echo ""
  echo "DBngin will appear in your menu bar for quick access"
uninstall: |
  echo "Uninstalling DBngin..."
  brew uninstall --cask dbngin
  echo "Note: Database files may remain and need manual cleanup"
