id: "marktext"
name: "MarkText"
description: "Simple and elegant Markdown editor"
type: "brew_cask"
category: "Utilities"
selected_by_default: false
requires_license: false
tags:
  - markdown
  - editor
  - writing
  - documentation
  - notes
  - wysiwyg
url: "https://marktext.app/"
notes: |
  - Simple and elegant Markdown editor with live preview
  - Real-time preview as you type
  - Support for tables, math expressions, and diagrams
  - Clean and distraction-free interface
  - Export to various formats including HTML and PDF
  - Free and open source
dependencies: []
install:
  script: |
    echo "Installing MarkText..."
    brew install --cask mark-text
validate:
  script: |
    brew list --cask | grep -q "mark-text" || ls /Applications/ | grep -q "MarkText.app"
configure:
  script: |
    echo "MarkText configuration complete"
    echo "Launch MarkText to start writing beautiful Markdown"
    echo ""
    echo "Key features:"
    echo "- WYSIWYG Markdown editor with real-time preview"
    echo "- Support for tables, math expressions, and flowcharts"
    echo "- Clean, distraction-free writing interface"
    echo "- Syntax highlighting and auto-completion"
    echo "- Export to HTML, PDF, and other formats"
    echo "- Theme customization and preferences"
    echo ""
    echo "Getting started:"
    echo "1. Launch MarkText from Applications"
    echo "2. Create a new document or open existing Markdown files"
    echo "3. Start writing with live preview"
    echo "4. Use toolbar for quick formatting"
    echo "5. Export your documents when ready"
    echo ""
    echo "Markdown features supported:"
    echo "- Headers, bold, italic, and basic formatting"
    echo "- Tables with advanced editing capabilities"
    echo "- Code blocks with syntax highlighting"
    echo "- Math expressions using KaTeX"
    echo "- Mermaid diagrams and flowcharts"
    echo "- Task lists and checkboxes"
    echo ""
    echo "Writing experience:"
    echo "- Real-time preview as you type"
    echo "- Focus mode for distraction-free writing"
    echo "- Typewriter mode with centered cursor"
    echo "- Source code mode for raw Markdown editing"
    echo "- Live table editing with visual feedback"
    echo ""
    echo "Export options:"
    echo "- HTML with custom CSS styling"
    echo "- PDF with print-ready formatting"
    echo "- Raw Markdown for sharing"
    echo "- Copy as HTML or styled text"
    echo ""
    echo "Customization:"
    echo "- Dark and light theme options"
    echo "- Font family and size preferences"
    echo "- Editor behavior settings"
    echo "- Custom CSS for exports"
    echo ""
    echo "Use cases:"
    echo "- Documentation writing"
    echo "- Blog post creation"
    echo "- README files for projects"
    echo "- Note-taking and journaling"
    echo "- Technical writing with math"
uninstall:
  script: |
    echo "Uninstalling MarkText..."
    brew uninstall --cask mark-text
