id: "virtualbox"
name: "VirtualBox"
description: "Open source virtualization platform"
type: "brew_cask"
category: "Utilities"
selected_by_default: false
requires_license: false
tags:
  - virtualization
  - vm
  - virtual-machine
  - oracle
  - development
  - testing
url: "https://www.virtualbox.org/"
notes: |
  - Open-source virtualization platform by Oracle
  - Run multiple operating systems simultaneously
  - Development, testing, and compatibility environments
  - Support for various guest operating systems
  - Snapshot and rollback capabilities
  - Free for personal and educational use
dependencies: []
bundle: cask "virtualbox"
install:
validate: |
  brew list --cask | grep -q "virtualbox" || ls /Applications/ | grep -q "VirtualBox.app"
configure: |
  echo "VirtualBox configuration complete"
  echo "Launch VirtualBox to start creating virtual machines"
  echo ""
  echo "Key features:"
  echo "- Support for Windows, Linux, macOS, and other OSes"
  echo "- Hardware virtualization and performance optimization"
  echo "- Snapshot and rollback functionality"
  echo "- Shared folders between host and guest"
  echo "- Network configuration and port forwarding"
  echo "- Guest Additions for enhanced integration"
  echo ""
  echo "Getting started:"
  echo "1. Launch VirtualBox from Applications"
  echo "2. Allow kernel extension in System Preferences if prompted"
  echo "3. Create a new virtual machine"
  echo "4. Install guest operating system from ISO"
  echo "5. Install Guest Additions for better integration"
  echo ""
  echo "System requirements:"
  echo "- At least 4GB RAM (8GB+ recommended)"
  echo "- Sufficient disk space for virtual machines"
  echo "- Intel VT-x or AMD-V virtualization support"
  echo "- macOS system permissions for kernel extensions"
  echo ""
  echo "Common use cases:"
  echo "- Testing software on different operating systems"
  echo "- Development environments and sandboxing"
  echo "- Running legacy applications"
  echo "- Educational and learning purposes"
  echo "- Malware analysis and security research"
  echo ""
  echo "Guest Additions benefits:"
  echo "- Better graphics and resolution support"
  echo "- Seamless mouse and keyboard integration"
  echo "- Shared clipboard functionality"
  echo "- Drag and drop file transfer"
  echo "- Shared folders between host and guest"
  echo ""
  echo "Performance tips:"
  echo "- Allocate appropriate RAM (not more than 50% of host)"
  echo "- Enable hardware acceleration when available"
  echo "- Use SSD storage for better VM performance"
  echo "- Install Guest Additions in each VM"
  echo ""
  echo "Note: Some features require Intel-based Macs"
  echo "Apple Silicon Macs have limited guest OS support"
uninstall: |
  echo "Uninstalling VirtualBox..."
  brew uninstall --cask virtualbox
  echo "Note: You may need to remove kernel extensions manually"
