id: "fzf"
name: "FZF"
description: "Command-line fuzzy finder for interactive filtering of files, command history, and processes"
type: "brew"
category: "Terminal"
selected_by_default: true
requires_license: false
tags:
  - fuzzy-finder
  - terminal
  - search
  - productivity
  - utilities
url: "https://github.com/junegunn/fzf"
notes: |
  - Command-line fuzzy finder for interactive filtering
  - Integrates with shell history, file search, and processes
  - Highly customizable with various key bindings
  - Works with any list: files, command history, processes, etc.
  - Supports preview window for files and commands
  - 
  - 📌 After installation:
  - 1. Run: $(brew --prefix)/opt/fzf/install
  - 2. Enable key bindings:
  -    • Ctrl-T: Search files and directories
  -    • Ctrl-R: Search command history
  -    • Alt-C: Change directory
  - 3. Restart terminal to use new key bindings
dependencies: []
install: |
  echo "Installing FZF..."
  brew install fzf
validate: |
  command -v fzf &> /dev/null
configure: |
  echo "FZF configuration complete"
  echo "Run: \$(brew --prefix)/opt/fzf/install"
  echo "This enables key bindings:"
  echo "  • Ctrl-T: Search files and directories"
  echo "  • Ctrl-R: Search command history"
  echo "  • Alt-C: Change directory"
  echo "Restart terminal to use new key bindings"
uninstall: |
  echo "Uninstalling FZF..."
  brew uninstall fzf
