id: "dock_settings"
name: "Dock Settings"
description: "Configure Dock auto-hide, size, and behavior"
type: "system_config"
category: "System Tweaks"
selected_by_default: true
requires_license: false
tags:
  - system-config
  - dock
  - ui
  - productivity
url: "https://support.apple.com/en-us/HT201730"
notes: |
  - Configures dock auto-hide for more screen space
  - Adjusts dock size and behavior preferences
  - Applies system-wide dock settings
  - No additional software required
dependencies: []
install: |
  echo "This item only configures existing system settings"
validate: |
  # Always return 1 (not configured) so configure script runs
  exit 1
configure: |
  echo "Applying Dock settings..."

  # Auto-hide the Dock
  defaults write com.apple.dock autohide -bool true

  # Set Dock size (0.0 = smallest, 1.0 = largest)
  defaults write com.apple.dock tilesize -int 48

  # Don't show recent applications in Dock
  defaults write com.apple.dock show-recents -bool false

  # Speed up Dock auto-hide animation
  defaults write com.apple.dock autohide-time-modifier -float 0.3

  # Remove delay for auto-hide
  defaults write com.apple.dock autohide-delay -float 0

  # Restart Dock to apply changes
  killall Dock

  echo "Dock settings applied successfully"
