id: "chrome"
name: "Google Chrome"
description: "Fast, secure, and free web browser"
type: "brew_cask"
category: "Browsers"
selected_by_default: true
requires_license: false
tags:
  - browser
  - web
  - google
  - essential
url: "https://www.google.com/chrome/"
notes: |
  - Most popular web browser with extensive extension ecosystem
  - Syncs with Google account for bookmarks, history, and passwords
  - Built-in developer tools and security features
  - Regular updates and security patches
dependencies: []
bundle: cask "google-chrome"
install:
validate: |
  brew list --cask | grep -q "google-chrome" || ls /Applications/ | grep -q "Google Chrome.app"
configure: |
  echo "Google Chrome configuration complete"
uninstall: |
  echo "Uninstalling Google Chrome..."
  brew uninstall --cask google-chrome
