id: "docker"
name: "Docker Desktop"
description: "Containerization platform for developers"
type: "brew_cask"
category: "Development"
dependencies: []
install:
  script: |
    echo "Installing Docker Desktop..."
    brew install --cask docker
validate:
  script: |
    brew list --cask | grep -q "docker" || ls /Applications/ | grep -q "Docker.app"
configure:
  script: |
    echo "Docker Desktop configuration complete"
    echo "Note: You may need to start Docker Desktop manually and grant permissions"
