id: "dock_settings"
name: "Dock Settings"
description: "Configure Dock auto-hide, size, and behavior"
type: "system_config"
category: "System Tweaks"
install:
  script: |
    echo "This item only configures existing system settings"
validate:
  script: |
    # Always return 1 (not configured) so configure script runs
    exit 1
configure:
  script: |
    echo "Applying Dock settings..."

    # Auto-hide the Dock
    defaults write com.apple.dock autohide -bool true

    # Set Dock size (0.0 = smallest, 1.0 = largest)
    defaults write com.apple.dock tilesize -int 48

    # Don't show recent applications in Dock
    defaults write com.apple.dock show-recents -bool false

    # Speed up Dock auto-hide animation
    defaults write com.apple.dock autohide-time-modifier -float 0.3

    # Remove delay for auto-hide
    defaults write com.apple.dock autohide-delay -float 0

    # Restart Dock to apply changes
    killall Dock

    echo "Dock settings applied successfully"
