id: "nginx"
name: "Nginx"
description: "HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server"
type: "brew"
category: "Development"
selected_by_default: false
requires_license: false
tags:
  - web-server
  - reverse-proxy
  - http
  - development
  - server
url: "https://nginx.org/"
notes: |
  - High-performance web server, reverse proxy, and load balancer
  - Lightweight and efficient for serving static content
  - Excellent for development and production environments
  - Supports SSL/TLS, HTTP/2, and WebSocket protocols
  - Highly configurable with modular architecture
dependencies: []
bundle: brew "nginx"
install:
validate: |
  command -v nginx &> /dev/null && brew services list | grep -q nginx
configure: |
  echo "Configuring Nginx..."

  # Create basic configuration
  CONFIG_DIR="/usr/local/etc/nginx"

  echo "Nginx configuration:"
  echo "- Config directory: $CONFIG_DIR"
  echo "- Main config file: $CONFIG_DIR/nginx.conf"
  echo "- Document root: /usr/local/var/www"
  echo ""
  echo "Basic commands:"
  echo "  brew services start nginx     # Start Nginx service"
  echo "  brew services stop nginx      # Stop Nginx service"
  echo "  brew services restart nginx   # Restart Nginx service"
  echo "  nginx -t                      # Test configuration"
  echo "  nginx -s reload               # Reload configuration"
  echo ""
  echo "Default server runs on: http://localhost:8080"
  echo "To start Nginx now: brew services start nginx"
uninstall: |
  echo "Stopping and uninstalling Nginx..."
  brew services stop nginx
  brew uninstall nginx
