id: "proto"
name: "Proto"
description: "Pluggable multi-language version manager with first-class support for toolchains and development environments"
type: "brew"
category: "Development"
selected_by_default: false
requires_license: false
tags:
  - version-manager
  - toolchain
  - development
  - multi-language
  - plugins
url: "https://moonrepo.dev/proto"
notes: |
  - Pluggable multi-language version manager
  - First-class support for toolchains and development environments
  - Plugin system for extending language support
  - Fast performance with Rust implementation
  - Supports Node.js, Python, Go, Rust, and more
  - 
  - 📌 After installation:
  - 1. Add to shell profile: eval "$(proto activate zsh)"
  - 2. Install a tool: proto install node
  - 3. Set global version: proto global node latest
  - 4. Create .prototools file in project: proto local node 18
dependencies: []
install:
  script: |
    echo "Installing Proto..."
    brew install proto
validate:
  script: |
    command -v proto &> /dev/null
configure:
  script: |
    echo "Proto configuration complete"
    echo "Add to shell profile: eval \"\$(proto activate zsh)\""
    echo "Install a tool: proto install node"
    echo "Set global version: proto global node latest"
    echo "Create .prototools file in projects: proto local node 18"
uninstall:
  script: |
    echo "Uninstalling Proto..."
    brew uninstall proto
