id: "google-drive"
name: "Google Drive"
description: "Cloud storage and file synchronization"
type: "brew_cask"
category: "Cloud"
selected_by_default: false
requires_license: false
tags:
  - cloud-storage
  - google
  - sync
  - backup
  - collaboration
url: "https://www.google.com/drive/"
notes: |
  - Google's cloud storage service with desktop sync
  - 15GB free storage shared across Google services
  - Real-time collaboration on Google Docs, Sheets, and Slides
  - File sharing with customizable permissions
  - Integration with Gmail and other Google services
  - Cross-platform synchronization
dependencies: []
bundle: cask "google-drive"
install:
validate: |
  brew list --cask | grep -q "google-drive" || ls /Applications/ | grep -q "Google Drive.app"
configure: |
  echo "Google Drive configuration complete"
  echo "Launch Google Drive and sign in with your Google account"
  echo "Key features:"
  echo "- Sync files across all your devices"
  echo "- Real-time collaboration in Google Workspace"
  echo "- File sharing with customizable permissions"
  echo "- Version history and file recovery"
  echo "- Integration with Gmail and Google Photos"
  echo "- Stream files (don't take up local space) or Mirror files (offline access)"
  echo ""
  echo "Note: Google Drive folder will be created and accessible in Finder"
  echo "Choose between 'Stream' or 'Mirror' sync options during setup"
uninstall: |
  echo "Uninstalling Google Drive..."
  brew uninstall --cask google-drive
  echo "Note: Google Drive folder and synced files will remain on your system"
