id: "rename"
name: "Rename"
description: "Perl-powered file rename script with many helpful built-ins"
type: "brew"
category: "Core Utilities"
selected_by_default: false
requires_license: false
tags:
  - file-management
  - rename
  - batch-operations
  - perl
  - utilities
url: "https://metacpan.org/pod/File::Rename"
notes: |
  - Command-line utility for batch renaming files using Perl expressions
  - Powerful pattern matching and substitution capabilities
  - Supports complex renaming operations with regular expressions
  - Dry-run mode to preview changes before applying
  - Case conversion and text manipulation features
dependencies: []
bundle: brew "rename"
install:
validate: |
  command -v rename &> /dev/null
configure: |
  echo "rename configuration complete"
  echo "Usage examples:"
  echo "  rename 's/old/new/' *.txt                # Replace 'old' with 'new' in .txt files"
  echo "  rename 'y/A-Z/a-z/' *                    # Convert filenames to lowercase"
  echo "  rename 's/ /_/g' *                       # Replace spaces with underscores"
  echo "  rename -n 's/old/new/' *.txt             # Dry-run (preview changes)"
  echo "  rename 's/^/prefix_/' *                   # Add prefix to all files"
  echo "  rename 's/\\.jpeg$/.jpg/' *               # Change .jpeg to .jpg"
  echo ""
  echo "Options:"
  echo "  -n    Dry-run (show what would be renamed without doing it)"
  echo "  -v    Verbose (show all renames as they happen)"
  echo ""
  echo "rename is now ready for batch file operations!"
uninstall: |
  echo "Uninstalling rename..."
  brew uninstall rename
