id: "bartender5"
name: "Bartender 5"
description: "Advanced menu bar icon organizer and manager"
type: "direct_download_dmg"
category: "Productivity"
selected_by_default: false
requires_license: true
tags:
  - menu-bar
  - organization
  - productivity
  - icons
  - management
  - workflow
url: "https://www.macbartender.com/"
notes: |
  - Advanced menu bar organization and management tool
  - Hide, show, and rearrange menu bar icons
  - Powerful automation and trigger system
  - Search functionality for quick access
  - Enhanced workflow and productivity
  - Premium software with free trial available
dependencies: []
install:
  script: |
    echo "Installing Bartender 5..."
    echo "Note: Bartender 5 is a premium application"
    echo ""
    echo "Installation options:"
    echo "1. Download from https://www.macbartender.com/"
    echo "2. Free trial available"
    echo "3. Purchase required for continued use"
    echo ""
    # Create temporary directory for download
    tmp_dir=$(mktemp -d)
    cd "$tmp_dir"

    echo "Downloading Bartender 5..."
    # Note: This would be the actual download URL
    download_url="https://www.macbartender.com/B2/updates/Bartender%205.zip"

    echo "Attempting to download from official website..."
    if command -v curl >/dev/null 2>&1; then
      echo "Using curl to download..."
      # curl -L -o "bartender5.zip" "$download_url"
      echo "Manual download required from official website"
    fi

    echo ""
    echo "Manual installation steps:"
    echo "1. Visit https://www.macbartender.com/"
    echo "2. Download Bartender 5 for macOS"
    echo "3. Open the downloaded ZIP/DMG file"
    echo "4. Move Bartender 5 to Applications folder"
    echo "5. Launch and start free trial or enter license"
validate:
  script: |
    # Check for Bartender 5 in Applications
    if ls /Applications/ | grep -q "Bartender 5.app"; then
      exit 0
    fi

    # Check for variations
    if ls /Applications/ | grep -i "bartender.*5" >/dev/null 2>&1; then
      exit 0
    fi

    echo "Bartender 5 not detected"
    exit 1
configure:
  script: |
    echo "Bartender 5 configuration complete"
    echo "Launch Bartender 5 to organize your menu bar"
    echo ""
    echo "Key features:"
    echo "- Hide and organize menu bar icons"
    echo "- Intelligent icon management and grouping"
    echo "- Search functionality for quick access"
    echo "- Trigger-based automation and rules"
    echo "- Keyboard shortcuts and hotkeys"
    echo "- Advanced customization options"
    echo ""
    echo "Getting started:"
    echo "1. Launch Bartender 5 from Applications"
    echo "2. Grant necessary system permissions"
    echo "3. Configure which icons to hide/show"
    echo "4. Set up triggers and automation rules"
    echo "5. Customize keyboard shortcuts"
    echo ""
    echo "Main features:"
    echo "- Menu Bar Items: Hide, show, and organize icons"
    echo "- Search: Quickly find and access hidden items"
    echo "- Triggers: Automate based on app states and conditions"
    echo "- Hotkeys: Keyboard shortcuts for instant access"
    echo "- Presets: Save and switch between configurations"
    echo ""
    echo "Advanced capabilities:"
    echo "- Time-based triggers (show/hide at specific times)"
    echo "- App-based triggers (show when certain apps run)"
    echo "- Battery and system status triggers"
    echo "- Custom spacing and arrangement"
    echo "- Icon grouping and categorization"
    echo ""
    echo "Productivity benefits:"
    echo "- Cleaner, organized menu bar appearance"
    echo "- Quick access to important items"
    echo "- Reduced visual clutter and distraction"
    echo "- Context-aware icon display"
    echo "- Enhanced focus and workflow"
    echo ""
    echo "Setup recommendations:"
    echo "1. Hide rarely used system icons"
    echo "2. Keep essential items always visible"
    echo "3. Set up triggers for contextual display"
    echo "4. Configure search hotkey for quick access"
    echo "5. Create presets for different work modes"
uninstall:
  script: |
    echo "Uninstalling Bartender 5..."
    find /Applications -name "*Bartender*5*" -delete 2>/dev/null || true
    echo "Note: Configuration preferences may remain in ~/Library"
