id: "cleanshotx"
name: "CleanShot X"
description: "Screenshot and screen recording tool"
type: "brew_cask"
category: "Productivity"
selected_by_default: false
requires_license: true
tags:
  - screenshot
  - screen-recording
  - productivity
  - annotation
  - cloud
url: "https://cleanshot.com/"
notes: |
  - Professional screenshot and screen recording with cloud integration
  - Advanced annotation tools and editing features
  - Scrolling capture for long web pages and documents
  - Built-in cloud storage and instant sharing
  - GIF creation and video editing capabilities
  - Requires subscription for full features
dependencies: []
bundle: cask "cleanshot"
install:
validate: |
  brew list --cask | grep -q "cleanshot" || ls /Applications/ | grep -q "CleanShot X.app"
configure: |
  echo "CleanShot X configuration complete"
  echo "Launch CleanShot X and configure your preferences"
  echo "Key features:"
  echo "- Advanced screenshot tools with annotation"
  echo "- Screen recording with editing capabilities"
  echo "- Scrolling capture for long content"
  echo "- Cloud storage and instant sharing"
  echo "- GIF creation and optimization"
  echo "- Custom keyboard shortcuts"
  echo ""
  echo "Note: CleanShot X offers a free trial"
  echo "Subscription required for cloud features and full functionality"
  echo "Configure keyboard shortcuts to replace default macOS screenshot tools"
uninstall: |
  echo "Uninstalling CleanShot X..."
  brew uninstall --cask cleanshot
