id: "finicky"
name: "Finicky"
description: "Default browser manager"
type: "brew"
category: "Productivity"
selected_by_default: false
requires_license: false
tags:
  - browser
  - productivity
  - automation
  - link-management
  - utilities
url: "https://github.com/johnste/finicky"
notes: |
  - Automatically opens links in the appropriate browser
  - Configurable rules based on URL patterns, domains, and conditions
  - Supports multiple browsers and applications
  - JavaScript-based configuration for complex rules
  - Open source and highly customizable
dependencies: []
install: |
  echo "Installing Finicky..."
  brew install --cask finicky
validate: |
  brew list --cask | grep -q "finicky" || ls /Applications/ | grep -q "Finicky.app"
configure: |
  echo "Configuring Finicky..."
  
  # Create basic configuration
  CONFIG_FILE="$HOME/.finicky.js"
  
  if [ ! -f "$CONFIG_FILE" ]; then
      cat > "$CONFIG_FILE" << 'EOF'
module.exports = {
  defaultBrowser: "Safari",
  handlers: [
  {
    // Open Gmail in Chrome
    match: /^https:\/\/mail\.google\.com/,
    browser: "Google Chrome"
  },
  {
    // Open GitHub in preferred browser
    match: /github\.com/,
    browser: "Google Chrome"
  },
  {
    // Open work domains in specific browser
    match: /company\.com/,
    browser: "Microsoft Edge"
  }
  ]
};
EOF
      echo "Created basic Finicky configuration at ~/.finicky.js"
  else
      echo "Finicky configuration already exists at ~/.finicky.js"
  fi
  
  echo "Finicky configuration complete"
  echo "Launch Finicky and set it as your default browser in System Preferences"
  echo ""
  echo "Configuration file: ~/.finicky.js"
  echo "Edit this file to customize browser routing rules"
  echo ""
  echo "Example rules are configured for:"
  echo "- Gmail -> Chrome"
  echo "- GitHub -> Chrome" 
  echo "- Default -> Safari"
uninstall: |
  echo "Uninstalling Finicky..."
  brew uninstall --cask finicky
  echo "Note: Configuration file ~/.finicky.js will remain" 